apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wzis0vtrm-python 
  janus-idp.io/tekton: wzis0vtrm-python
  backstage.io/kubernetes-id: wzis0vtrm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wzis0vtrm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml